### ISSUE TITLE
Failed to stage scipy with flask

### ISSUE THREAD

**Issue by yishaishimoni** [IBM-Bluemix/python-buildpack-scipy#1]
I am trying to deploy a flask-based web-app that is running without problems locally and depends on scipy.
I have the following `manifest.yml`:

```
buildpack: https://github.com/IBM-Bluemix/python-buildpack-scipy.git
```

and the following `requirements.txt`:

```
Flask==0.10.1 
numpy==1.9.1 
scipy==0.15.1
```

The code I run to connect and load the app is as follows:

```
bluemix api https://api.ng.bluemix.net
bluemix login -u <my_user_id> -o <my_user_id> -s dev
cf push <my_app_name> -m 512M
```

I am getting the following error (both on the United-Kingdom server and on the US South server):

```
Starting app SCUP_demo in org yishais@il.ibm.com / space dev as yishais@il.ibm.com...
-----> Downloaded app package (212K)
    Cloning into '/tmp/buildpacks/python-buildpack-scipy'...
    -----> Installing runtime (python-2.7.9)
-----> Installing dependencies with pip
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/app/.heroku/python/bin/pip", line 9, in <module>
    load_entry_point('pip==6.0.6', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 519, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2310, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2316, in resolve
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/vcs/mercurial.py", line 11, in <module>
    from pip.download import path_to_url
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/download.py", line 30, in <module>
    from pip._vendor import requests, six
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/__init__.py", line 81, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.requests'
Staging failed: Buildpack compilation step failed

FAILED
```

**Comment by opiethehokie** [comment]
I'm hitting this error too, but I think flask is a red herring. I'm seeing it with just numpy and scipy. Same issue here - https://github.com/thenovices/heroku-buildpack-scipy/issues/30.

Is the buildpack supposed to work on the cflinuxfs2 stack?

**Comment by cphrmky** [comment]
@opiethehokie when first put it up, this build pack was working properly on Bluemix with cflinuxfs2.

Shortly thereafter the Bluemix operations team upgraded a patch of cflinuxfs2 (I believe) and it broke.  

Flask is for sure a red herring, it's the installation of `scipy` that breaks things.  In fact, I think the buildpack itself works if you don't have `scipy` in your `requirements.txt` when you push an app (sort of defeats the point of course).

So, yes it's supposed to work.  No it presently doesn't work.  I poked around looking for a solution I could apply from userland but haven't found one at this point.

I'll see what I can do to get some attention drawn to this by someone who could get a fix identified and into the pipeline for the next time they patch.

**Comment by johndeepu** [comment]
@cphrmky same error here. Any fixes yet?
